Config = {}

Config.BlacklistedWords = {
    "nigger",
    "niggers",
    "Desudo",
    "Brutan",
    "EulenCheats",
    "lynxmenu",
    "HamHaxia",
    "Ham Mafia",
    "www.renalua.com",
    "Fallen#0811",
    "Rena 8",
    "HamHaxia",
    "Ham Mafia",
    "Xanax#0134",
    ">:D Player Crash",
    "34ByTe Community",
    "lynxmenu.com",
    "Anti-LRAC",
    "Baran#8992",
    "iLostName#7138",
    "85.190.90.118",
    "Melon#1379",
    "hammafia.com",
    "AlphaV ~ 5391",
    "vjuton.pl",
    "XARIES",
    "xaries",
    "dc.xaries.pl",
    "aries",
    "aries.pl",
    "youtube.com/c/Aries98/",
    "Aries98",
    "333GANG",
    "Desudo",
    "Brutan",
    "EulenCheats",
    "Lynx 8",
    "www.lynxmenu.com",
    "HamHaxia",
    "Ham Mafia",
    "www.renalua.com",
    "Fallen#0811",
    "Rena 8",
    "HamHaxia",
    "Ham Mafia",
    "Xanax#0134",
    ">:D Player Crash",
    "34ByTe Community",
    "lynxmenu.com",
    "Anti-Lynx",
    "Baran#8992",
    "iLostName#7138",
    "85.190.90.118",
    "hammafia.com",
    "AlphaV ~ 5391",
    "vjuton.pl",
    "EulenCheat",
    "Eulen",
    "lynxmenu",
    "Lynx",
    "lynxmenu.com - Cheats & Anti-Cheats!"
}

BlacklistedEntities = {
    "prop_fnclink_05crnr1",
    "xs_prop_hamburgher_wl",
    "xs_prop_plastic_bottle_wl",
    "prop_windmill_01",
    "p_spinning_anus_s",
    "stt_prop_ramp_adj_flip_m",
    "stt_prop_ramp_adj_flip_mb",
    "stt_prop_ramp_adj_flip_s",
    "stt_prop_ramp_adj_flip_sb",
    "stt_prop_ramp_adj_hloop",
    "stt_prop_ramp_adj_loop",
    "stt_prop_ramp_jump_l",
    "stt_prop_ramp_jump_m",
    "stt_prop_ramp_jump_s",
    "stt_prop_ramp_jump_xl",
    "stt_prop_ramp_jump_xs",
    "stt_prop_ramp_jump_xxl",
    "stt_prop_ramp_multi_loop_rb",
    "stt_prop_ramp_spiral_l",
    "stt_prop_ramp_spiral_l_l",
    "stt_prop_ramp_spiral_l_m",
    "stt_prop_ramp_spiral_l_s",
    "stt_prop_ramp_spiral_l_xxl",
    "stt_prop_ramp_spiral_m",
    "stt_prop_ramp_spiral_s",
    "stt_prop_ramp_spiral_xxl",
    "stt_prop_hoop_constraction_01a",
    "stt_prop_hoop_small_01",
    "stt_prop_hoop_tyre_01a",
    "stt_prop_race_start_line_01",
    "stt_prop_race_start_line_01b",
    "stt_prop_race_start_line_02",
    "stt_prop_race_start_line_02b",
    "stt_prop_race_start_line_03",
    "stt_prop_race_start_line_03b",
    "stt_prop_stunt_bblock_huge_01",
    "stt_prop_stunt_bblock_huge_02",
    "stt_prop_stunt_bblock_huge_03",
    "stt_prop_stunt_bblock_huge_04",
    "stt_prop_stunt_bblock_lrg1",
    "stt_prop_stunt_bblock_lrg2",
    "stt_prop_stunt_bblock_lrg3",
    "stt_prop_stunt_bblock_mdm1",
    "stt_prop_stunt_bblock_mdm2",
    "stt_prop_stunt_bblock_mdm3",
    "stt_prop_stunt_bblock_qp",
    "stt_prop_stunt_bblock_qp2",
    "stt_prop_stunt_bblock_qp3",
    "stt_prop_stunt_bblock_sml1",
    "stt_prop_stunt_bblock_sml2",
    "stt_prop_stunt_bblock_sml3",
    "stt_prop_stunt_bblock_xl1",
    "stt_prop_stunt_bblock_xl2",
    "stt_prop_stunt_bblock_xl3",
    "stt_prop_stunt_bowling_pin",
    "stt_prop_stunt_bowling_ball",
    "stt_prop_stunt_bowlpin_stand",
    "stt_prop_stunt_domino",
    "stt_prop_stunt_jump15",
    "stt_prop_stunt_jump30",
    "stt_prop_stunt_jump45",
    "stt_prop_stunt_jump_l",
    "stt_prop_stunt_jump_lb",
    "stt_prop_stunt_jump_m",
    "stt_prop_stunt_jump_mb",
    "stt_prop_stunt_jump_s",
    "stt_prop_stunt_landing_zone_01",
    "stt_prop_stunt_ramp",
    "stt_prop_stunt_target",
    "stt_prop_stunt_track_bumps",
    "stt_prop_stunt_track_dwlink_02",
    "stt_prop_stunt_track_dwsh15",
    "stt_prop_stunt_track_dwslope45",
    "stt_prop_stunt_track_dwslope30",
    "stt_prop_stunt_track_dwslope15",
    "stt_prop_stunt_track_dwturn",
    "stt_prop_stunt_track_dwuturn",
    "stt_prop_stunt_track_exshort",
    "stt_prop_stunt_track_fork",
    "stt_prop_stunt_track_funlng",
    "stt_prop_stunt_track_funnel",
    "stt_prop_stunt_track_hill",
    "stt_prop_stunt_track_hill2",
    "stt_prop_stunt_track_jump",
    "stt_prop_stunt_track_link",
    "stt_prop_stunt_track_otake",
    "stt_prop_stunt_track_sh15",
    "stt_prop_stunt_track_sh30",
    "stt_prop_stunt_track_sh45",
    "stt_prop_stunt_track_slope15",
    "stt_prop_stunt_track_slope30",
    "stt_prop_stunt_track_slope45",
    "stt_prop_stunt_track_st_01",
    "stt_prop_stunt_track_st_02",
    "stt_prop_stunt_track_start",
    "stt_prop_stunt_track_start_02",
    "stt_prop_stunt_track_turnice",
    "stt_prop_stunt_track_uturn",
    "stt_prop_stunt_tube_crn",
    "stt_prop_stunt_tube_crn2",
    "stt_prop_stunt_tube_crn_15d",
    "stt_prop_stunt_tube_crn_30d",
    "stt_prop_stunt_tube_crn_5d",
    "stt_prop_stunt_tube_cross",
    "stt_prop_stunt_tube_end",
    "stt_prop_stunt_tube_ent",
    "stt_prop_stunt_tube_fn_01",
    "stt_prop_stunt_tube_fn_02",
    "stt_prop_stunt_tube_fn_03",
    "stt_prop_stunt_tube_fn_04",
    "stt_prop_stunt_tube_fn_05",
    "stt_prop_stunt_tube_fork",
    "stt_prop_stunt_tube_gap_01",
    "stt_prop_stunt_tube_gap_02",
    "stt_prop_stunt_tube_gap_03",
    "stt_prop_stunt_tube_hg",
    "stt_prop_stunt_tube_jmp",
    "stt_prop_stunt_tube_jmp2",
    "stt_prop_stunt_tube_l",
    "stt_prop_stunt_tube_m",
    "stt_prop_stunt_tube_qg",
    "stt_prop_stunt_tube_s",
    "stt_prop_stunt_tube_speed",
    "stt_prop_stunt_tube_speeda",
    "stt_prop_stunt_tube_speedb",
    "stt_prop_stunt_tube_xs",
    "stt_prop_stunt_tube_xxs",
    "stt_prop_stunt_wideramp",
    "stt_prop_track_bend2_bar_l_b",
    "stt_prop_track_bend2_l",
    "stt_prop_track_bend2_l_b",
    "stt_prop_track_bend_15d",
    "stt_prop_track_bend_15d_bar",
    "stt_prop_track_bend_180d",
    "stt_prop_track_bend_180d_bar",
    "stt_prop_track_bend_30d",
    "stt_prop_track_bend_30d_bar",
    "stt_prop_track_bend_5d",
    "stt_prop_track_bend_5d_bar",
    "stt_prop_track_bend_bar_l",
    "stt_prop_track_bend_bar_l_b",
    "stt_prop_track_bend_bar_m",
    "stt_prop_track_bend_l",
    "stt_prop_track_bend_l_b",
    "stt_prop_track_bend_m",
    "stt_prop_track_bend_l",
    "stt_prop_track_bend_l_b",
    "stt_prop_track_bend_m",
    "stt_prop_track_block_01",
    "stt_prop_track_block_02",
    "stt_prop_track_block_03",
    "stt_prop_track_chicane_l",
    "stt_prop_track_chicane_r",
    "stt_prop_track_chicane_l_02",
    "stt_prop_track_chicane_r_02",
    "stt_prop_track_cross",
    "stt_prop_track_cross_bar",
    "stt_prop_track_fork_bar",
    "stt_prop_track_funnel",
    "stt_prop_track_funnel_ads_01a",
    "stt_prop_track_funnel_ads_01b",
    "stt_prop_track_funnel_ads_01c",
    "stt_prop_track_jump_01a",
    "stt_prop_track_jump_01b",
    "stt_prop_track_jump_01c",
    "stt_prop_track_jump_02a",
    "stt_prop_track_jump_02b",
    "stt_prop_track_jump_02c",
    "stt_prop_track_link",
    "stt_prop_track_slowdown",
    "stt_prop_track_slowdown_t1",
    "stt_prop_track_slowdown_t2",
    "stt_prop_track_speedup",
    "stt_prop_track_speedup_t1",
    "stt_prop_track_speedup_t2",
    "stt_prop_track_start",
    "stt_prop_track_start_02",
    "stt_prop_track_straight_bar_m",
    "stt_prop_track_straight_bar_l",
    "stt_prop_track_straight_bar_s",
    "stt_prop_track_straight_l",
    "stt_prop_track_straight_lm",
    "stt_prop_track_straight_lm_bar",
    "stt_prop_track_straight_m",
    "stt_prop_track_straight_s",
    "stt_prop_track_tube_01",
    "stt_prop_track_tube_02",
    "stt_prop_tyre_wall_01",
    "stt_prop_wallride_01",
    "stt_prop_wallride_01b",
    "stt_prop_wallride_02",
    "stt_prop_wallride_02b",
    "stt_prop_wallride_04",
    "stt_prop_wallride_05",
    "stt_prop_wallride_05b",
    "stt_prop_wallride_45l",
    "stt_prop_wallride_45la",
    "stt_prop_wallride_45r",
    "stt_prop_wallride_45ra",
    "stt_prop_wallride_90l",
    "stt_prop_wallride_90lb",
    "stt_prop_wallride_90r",
    "stt_prop_wallride_90rb",
    "prop_beach_fire",
    "hei_prop_heist_tug",
    "p_cs_mp_jet_01_s",
    "p_med_jet_01_s",
    "prop_bumper_car_01",
    "prop_med_jet_01",
    "prop_barrier_wat_03a",
    "prop_roadcone01a",
    "prop_roadcone01b",
    "prop_roadcone01c",
    "p_cs_15m_rope_s",
    "stt_prop_stunt_target_small",
    "stt_prop_stunt_soccer_ball",
    "stt_prop_stunt_soccer_sball",
    "prop_dummy_01",
    "prop_phys_wades_head",
    "prop_water_corpse_01",
    "prop_water_corpse_02",
    "xs_propint3_waste_01_statues",
    "cargoplane",
    "vigilante",
    "hydra",
    "deluxo",
    "avenger",
    "akula",
    "apc",
    "barrage",
    "caracara",
    -- "cargobob",
    "chernobog",
    "hunter",
    "insurgent",
    "insurgent2",
    "insurgent3",
    "starling",
    -- "lazer",
    "bombushka",
    "savage",
    "rhino",
    "khanjali",
    "Blimp2",
    -- "Cuban800",
    "Dodo",
    "Duster",
    -- "Jet",
    "akula",
    "Tug",
    "prop_coffin_01",
    "prop_coffin_02",
    "prop_coffin_02b",
    "prop_beach_fire",
    "prop_gas_pump_1a",
    "prop_gas_pump_1b",
    "prop_gas_pump_1c",
    "prop_gas_pump_1d",
    "prop_gas_pump_old2",
    "prop_gas_pump_old3",
    "prop_vintage_pump",
    "prop_asteroid_01",
    "prop_dog_cage_01",
    "prop_dog_cage_02",
    "prop_ferris_car_01",
    "p_ferris_car_01",
    "prop_ld_ferris_wheel",
    "prop_bumper_car_01",
    "prop_gold_cont_01",
    "prop_gold_cont_01b",
    "p_spinning_anus_s",
    "Freight",
    "technical",
    "technical2",
    "technical3",
    "prop_xmas_tree_int",
    "prop_xmas_ext",
    "dt1_05_build1_damage_lod",
    "dt1_05_damage_slod",
    "v_ilev_go_window",
    "hei_prop_heist_roller",
    -- VANILLA BUT DOESN'T SPAWN
    "dune2",
    "dune3",
    "dune4",
    "dune5",
    -- DLC VEHICLES
    "asbo",
    "brioso",
    "brioso2",
    "club",
    "kanjo",
    "issi3",
    "issi4",
    "issi5",
    "issi6",
    "weevil",
    "halftrack",
    "minitank",
    "scarab",
    "scarab2",
    "scarab3",
    "thruster",
    "alkonost",
    "avisa",
    "dinghy5",
    "kosatka",
    "longfin",
    "patrolboat",
    "cerberus",
    "cerberus2",
    "cerberus3",
    "annihilator2",
    "seasparrow2",
    "seasparrow3",
    "rcbandito",
    "zr380",
    "zr3802",
    "zr3803",
    "oppressor",
    "oppressor2",
    "bruiser",
    "bruiser2",
    "bruiser3",
    "brutus",
    "brutus2",
    "brutus3",
    "monster3",
    "monster4",
    "monster5",
    "nightshark",
    "deathbike",
    "deathbike2",
    "deathbike3",
    -- "manchez2",
    "clique",
    "deviant",
    "ela_wdn_02lod_",
    "ela_wdn_04lod_",
    "apa_mp_apa_crashed_usaf_01a",
    "apa_mp_apa_yacht",
    "prop_doghouse_01",
    "prop_ld_toilet_01",
    "prop_toilet_01",
    "prop_toilet_02"
}

Config.GameWeapons = {
    "WEAPON_SNSPISTOL",
    "WEAPON_DOUBLEACTION",
    "WEAPON_REVOLVER",
    "WEAPON_APPISTOL",
    "WEAPON_ASSAULTRIFLE",
    "WEAPON_SMG",
    "WEAPON_DBSHOTGUN",
    "WEAPON_SAWNOFFSHOTGUN",
    "WEAPON_SWITCHBLADE",
    "WEAPON_MACHETE",
    "WEAPON_MUSKET",
    "WEAPON_BAT",
    "WEAPON_M9",
    "WEAPON_P226",
    "WEAPON_1911",
    "WEAPON_FNFAL",
    "WEAPON_MAC10",
    "WEAPON_WALTHER",
    "WEAPON_TACTICALRIFLE"
}

Config.BlacklistedWeapons = {
    "WEAPON_BULLPUPSHOTGUN",
    -- "WEAPON_GRENADELAUNCHER",
    -- "WEAPON_GRENADELAUNCHER_SMOKE",
    "WEAPON_RPG",
    "WEAPON_STINGER",
    "WEAPON_MINIGUN",
    "WEAPON_GRENADE",
    "WEAPON_BALL",
    "WEAPON_HEAVYSHOTGUN",
    -- "WEAPON_GARBAGEBAG",
    "WEAPON_RAILPISTOL",
    "WEAPON_RAILGUN",
    "WEAPON_RAYPISTOL",
    "WEAPON_RAYCARBINE",
    "WEAPON_RAYMINIGUN",
    "WEAPON_DIGISCANNER",
    "WEAPON_SPECIALCARBINE_MK2",
    "WEAPON_BULLPUPRIFLE_MK2",
    "WEAPON_PUMPSHOTGUN_MK2",
    "WEAPON_COMPACTLAUNCHER",
    "WEAPON_SNSPISTOL_MK2",
    "WEAPON_REVOLVER_MK2",
    "WEAPON_HOMINGLAUNCHER",
    "WEAPON_SMG_MK2",
    "WEAPON_COMBATPDW",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_SNIPERRIFLE",
    "WEAPON_HEAVYSNIPER",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_MARKSMANRIFLE",
    "WEAPON_MARKSMANRIFLE_MK2",
    -- "WEAPON_MUSKET",
    "WEAPON_MG",
    "WEAPON_COMBATMG",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_GUSENBERG",
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_SPECIALCARBINE",
    "WEAPON_COMPACTRIFLE",
    "WEAPON_AUTOSHOTGUN",
    "WEAPON_ASSAULTSHOTGUN",
    -- "WEAPON_SAWNOFFSHOTGUN",
    "WEAPON_MICROSMG",
    "WEAPON_ASSAULTSMG",
    "WEAPON_MACHINEPISTOL",
    "WEAPON_MINISMG",
    "WEAPON_RAYCARBINE",
    "WEAPON_PISTOL",
    "WEAPON_PISTOL_MK2",
    "WEAPON_HEAVYPISTOL",
    "WEAPON_MARKSMANPISTOL",
    "WEAPON_PISTOL50",
    "WEAPON_RAYPISTOL",
    "WEAPON_FLAREGUN",
    "WEAPON_KNUCKLE",
    "WEAPON_DAGGER",
    "WEAPON_POOLCUE"
}

Config.BlacklistedCommands = {
    ["chocolate"] = true,
    -- ["pk"] = true,
    ["haha"] = true,
    ["lol"] = true,
    ["panickey"] = true,
    ["killmenu"] = true,
    ["panik"] = true,
    ["lynx"] = true,
    ["brutan"] = true,
    ["panic"] = true,
    ["purgemenu"] = true
}

if not IsDuplicityVersion() then
    Config.BlacklistedComponents = {
        [`WEAPON_APPISTOL`] = {
            `COMPONENT_APPISTOL_CLIP_02`,
            `COMPONENT_AT_PI_FLSH`,
            `COMPONENT_AT_PI_SUPP`
        },
        [`WEAPON_ASSAULTRIFLE`] = {
            `COMPONENT_ASSAULTRIFLE_CLIP_02`,
            `COMPONENT_ASSAULTRIFLE_CLIP_03`,
            `COMPONENT_AT_AR_FLSH`,
            `COMPONENT_AT_SCOPE_MACRO`,
            `COMPONENT_AT_AR_SUPP_02`,
            `COMPONENT_AT_AR_AFGRIP`
        },
        [`WEAPON_SMG`] = {
            `COMPONENT_SMG_CLIP_02`,
            `COMPONENT_SMG_CLIP_03`,
            `COMPONENT_AT_AR_FLSH`,
            `COMPONENT_AT_SCOPE_MACRO_02`,
            `COMPONENT_AT_PI_SUPP`
        }
    }
end